/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.UsuarioDAO;
import factory.ConnectionFactory;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.CanaisDTO;

public class frmCriarAdminGUI extends javax.swing.JFrame {

    /**
     * Creates new form editar_canal
     */
    public frmCriarAdminGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        canal = new javax.swing.JLabel();
        tipoCanal = new javax.swing.JLabel();
        padraoAut = new javax.swing.JLabel();
        txtCanal = new javax.swing.JTextField();
        txtAutentica = new javax.swing.JComboBox<>();
        txtTipo = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        botao_voltar = new javax.swing.JButton();
        fundo_editar_canal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        titulo.setForeground(new java.awt.Color(51, 0, 51));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("CRIAR CANAIS");
        titulo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 0)));
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 280, 80));

        canal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        canal.setForeground(new java.awt.Color(51, 0, 51));
        canal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        canal.setText("CANAL");
        getContentPane().add(canal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 70, 29));

        tipoCanal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tipoCanal.setForeground(new java.awt.Color(51, 0, 51));
        tipoCanal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipoCanal.setText("TIPO DE CANAL");
        getContentPane().add(tipoCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 160, -1));

        padraoAut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        padraoAut.setForeground(new java.awt.Color(51, 0, 51));
        padraoAut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        padraoAut.setText("PADRÃO DE AUTENTIFICAÇÃO");
        getContentPane().add(padraoAut, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 310, -1));

        txtCanal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCanal.setForeground(new java.awt.Color(255, 102, 0));
        txtCanal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 0)));
        txtCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCanalActionPerformed(evt);
            }
        });
        getContentPane().add(txtCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 270, 40));

        txtAutentica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAutentica.setForeground(new java.awt.Color(255, 102, 0));
        txtAutentica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário/ senha", "Token" }));
        txtAutentica.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 0)));
        getContentPane().add(txtAutentica, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 270, 40));

        txtTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(255, 102, 0));
        txtTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plataforma/ ERP", "Marketplace", "Meio de pagamento" }));
        txtTipo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 0)));
        getContentPane().add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 270, 40));

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(102, 0, 102));
        btnCadastrar.setText("SALVAR");
        btnCadastrar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 0)));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 650, 100, 40));

        botao_voltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botao_voltar.setForeground(new java.awt.Color(102, 0, 102));
        botao_voltar.setText("VOLTAR");
        botao_voltar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 51, 0)));
        botao_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(botao_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 640, 90, 40));

        fundo_editar_canal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fundo_editar_canal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_padrao.png"))); // NOI18N
        getContentPane().add(fundo_editar_canal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCanalActionPerformed

    }//GEN-LAST:event_txtCanalActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String canalamd, tipoadm, autentica;

        canalamd = txtCanal.getText();
        tipoadm = txtTipo.getSelectedItem().toString();
        autentica = txtAutentica.getSelectedItem().toString();

        CanaisDTO objCanaisDTO = new CanaisDTO();
        objCanaisDTO.setCanalamd(canalamd);
        objCanaisDTO.setTipoadm(tipoadm);
        objCanaisDTO.setAutentica(autentica);

        UsuarioDAO objCanalDAO = new UsuarioDAO();
        objCanalDAO.cadastrarCanaladm(objCanaisDTO);

        JOptionPane.showMessageDialog(null, "Cadastro feito!");

        frmHomeAdminGUI objhomeadmgui = new frmHomeAdminGUI();
        objhomeadmgui.setVisible(true); //abri a pagina se o login for correto

        dispose(); //abri a pagina se o login for correto


    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void botao_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_voltarActionPerformed
        frmHomeAdminGUI objfrmhomeadmingui = new frmHomeAdminGUI();
        objfrmhomeadmingui.setVisible(true); //abri a pagina se o login for correto

        dispose();
    }//GEN-LAST:event_botao_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */


 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCriarAdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_voltar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel canal;
    private javax.swing.JLabel fundo_editar_canal;
    private javax.swing.JLabel padraoAut;
    private javax.swing.JLabel tipoCanal;
    private javax.swing.JLabel titulo;
    private javax.swing.JComboBox<String> txtAutentica;
    private javax.swing.JTextField txtCanal;
    private javax.swing.JComboBox<String> txtTipo;
    // End of variables declaration//GEN-END:variables

}
