/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.UsuarioDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.Login;

/**
 *
 * @author debor
 */
public class frmLoginAdmGUI extends javax.swing.JFrame {

    /**
     * Creates new form entrada_admin
     */
    public frmLoginAdmGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        senha_admin = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        botaoEntrar = new javax.swing.JButton();
        botao_voltar = new javax.swing.JButton();
        fundo_entrada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        senha_admin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        senha_admin.setForeground(new java.awt.Color(51, 0, 51));
        senha_admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senha_admin.setText("SENHA ADMINISTRADOR:");
        getContentPane().add(senha_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 480, 100));

        txtSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 0)));
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 410, 40));

        botaoEntrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoEntrar.setForeground(new java.awt.Color(102, 0, 102));
        botaoEntrar.setText("ENTRAR");
        botaoEntrar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 51, 0)));
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, 140, 70));

        botao_voltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botao_voltar.setForeground(new java.awt.Color(102, 0, 102));
        botao_voltar.setText("VOLTAR");
        botao_voltar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 51, 0)));
        botao_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(botao_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 140, 70));

        fundo_entrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fundo_entrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_entrada.png"))); // NOI18N
        getContentPane().add(fundo_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1018, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        try {
            String senha;

            senha = txtSenha.getText();

            Login objlogin = new Login();
            objlogin.setSenha(senha);

            UsuarioDAO objlogindao = new UsuarioDAO();
            ResultSet rslogindao = objlogindao.autenticacaoUsuario(objlogin);
            
            if (rslogindao.next()) {
                //chamar tela que eu quero abrir
                frmHomeAdminGUI objhomeadmgui = new frmHomeAdminGUI();
                objhomeadmgui.setVisible(true); //abri a pagina se o login for correto
                
                dispose(); //fecha a tela de login
            } else {
                //enviar mensagem dizendo erro
                JOptionPane.showMessageDialog(null, "Usuario ou senha incorreta");
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,"FRMLoginGUI"  + erro);
            
        }

                
    }//GEN-LAST:event_botaoEntrarActionPerformed

    private void botao_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_voltarActionPerformed
        frmAnteLoginGUI objfrmantelogingui = new frmAnteLoginGUI();
        objfrmantelogingui.setVisible(true); //abri a pagina se o login for correto

        dispose();
    }//GEN-LAST:event_botao_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLoginAdmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLoginAdmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLoginAdmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLoginAdmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLoginAdmGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JButton botao_voltar;
    private javax.swing.JLabel fundo_entrada;
    private javax.swing.JLabel senha_admin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
