/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author debor
 */
public class frmAnteLoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form login_geral
     */
    public frmAnteLoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdmin = new javax.swing.JButton();
        borda_botao_admin = new javax.swing.JLabel();
        btnVizualizar = new javax.swing.JButton();
        borda_botao_usuario = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(102, 0, 102));
        btnAdmin.setText("Administrador");
        btnAdmin.setBorder(null);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 240, 120));

        borda_botao_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/borda_botao.png"))); // NOI18N
        getContentPane().add(borda_botao_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, 160));

        btnVizualizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnVizualizar.setForeground(new java.awt.Color(102, 0, 102));
        btnVizualizar.setText("Usuário");
        btnVizualizar.setBorder(null);
        btnVizualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVizualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVizualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 240, 130));

        borda_botao_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/borda_botao.png"))); // NOI18N
        getContentPane().add(borda_botao_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, 150));

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(51, 0, 51));
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("LOGIN");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 160, 70));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_entrada.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1015, 714));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        frmLoginAdmGUI objadmlogingui = new frmLoginAdmGUI();
        objadmlogingui.setVisible(true); //abri a pagina se o login for correto
                
        dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnVizualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVizualizarActionPerformed
 
        frmListaUserGUI objListausergui = new frmListaUserGUI();
        objListausergui.setVisible(true); //abri a pagina se o login for correto
                
        dispose(); //fecha a tela de login
                                             
    }//GEN-LAST:event_btnVizualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAnteLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAnteLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAnteLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAnteLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAnteLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel borda_botao_admin;
    private javax.swing.JLabel borda_botao_usuario;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnVizualizar;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel login;
    // End of variables declaration//GEN-END:variables
}
