/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author debor
 */
public class frmHomeAdminGUI extends javax.swing.JFrame {

    /**
     * Creates new form home_admin
     */
    public frmHomeAdminGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_criar_novo_canal = new javax.swing.JButton();
        borda_botao_admin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        borda_botao_usuario = new javax.swing.JLabel();
        botao_voltar = new javax.swing.JButton();
        fundo_home = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao_criar_novo_canal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botao_criar_novo_canal.setForeground(new java.awt.Color(102, 0, 102));
        botao_criar_novo_canal.setText("Criar Novo Canal");
        botao_criar_novo_canal.setBorder(null);
        botao_criar_novo_canal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_criar_novo_canalActionPerformed(evt);
            }
        });
        getContentPane().add(botao_criar_novo_canal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 240, 130));

        borda_botao_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/borda_botao.png"))); // NOI18N
        getContentPane().add(borda_botao_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, 170));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("Visualizar Canais");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 240, 130));

        borda_botao_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/borda_botao.png"))); // NOI18N
        getContentPane().add(borda_botao_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, 170));

        botao_voltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botao_voltar.setForeground(new java.awt.Color(102, 0, 102));
        botao_voltar.setText("VOLTAR");
        botao_voltar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 51, 0)));
        botao_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(botao_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, 90, 40));

        fundo_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_entrada.png"))); // NOI18N
        fundo_home.setText("jLabel1");
        getContentPane().add(fundo_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1016, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmListaGUI objListagui = new frmListaGUI();
        objListagui.setVisible(true); //abri a pagina se o login for correto
                
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botao_criar_novo_canalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_criar_novo_canalActionPerformed
         frmCriarAdminGUI objcriaradmingui = new frmCriarAdminGUI();
        objcriaradmingui.setVisible(true); //abri a pagina se o login for correto

        dispose();
    }//GEN-LAST:event_botao_criar_novo_canalActionPerformed

    private void botao_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_voltarActionPerformed
        frmAnteLoginGUI objfrmantelogingui = new frmAnteLoginGUI();
        objfrmantelogingui.setVisible(true); //abri a pagina se o login for correto

        dispose();
    }//GEN-LAST:event_botao_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHomeAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHomeAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHomeAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHomeAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHomeAdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel borda_botao_admin;
    private javax.swing.JLabel borda_botao_usuario;
    private javax.swing.JButton botao_criar_novo_canal;
    private javax.swing.JButton botao_voltar;
    private javax.swing.JLabel fundo_home;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
