/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.UsuarioDAO;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import modelo.CanaisDTO;

/**
 *
 * @author Pedro
 */

public class frmListaUserGUI extends javax.swing.JFrame {

    /**
     * Creates new form frmListaGUI
     */
    UsuarioDAO DAO;
    public frmListaUserGUI() {
        initComponents();
        ListarValoresCanais();
        try {
           DAO = new UsuarioDAO();            
    }  catch (Exception e) {   
    }
}  
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCanais = new javax.swing.JTable();
        btnCadastrarCanal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Pesquise = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CarTipo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CarUsuario = new javax.swing.JTextField();
        CarNome = new javax.swing.JTextField();
        CarToken = new javax.swing.JTextField();
        CarCanal = new javax.swing.JTextField();
        CarSenha = new javax.swing.JPasswordField();
        btnExcluir = new javax.swing.JButton();
        CarregarCampos = new javax.swing.JButton();
        CarID = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pesquisa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 90, 40));

        tabelaCanais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Canal", "Tipo", "Usuario", "Senha", "Token"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaCanais);
        if (tabelaCanais.getColumnModel().getColumnCount() > 0) {
            tabelaCanais.getColumnModel().getColumn(0).setResizable(false);
            tabelaCanais.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 767, 178));

        btnCadastrarCanal.setText("Cadastrar Canal");
        btnCadastrarCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCanalActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 140, 46));

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 377, -1, -1));

        jLabel2.setText("Canal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        jLabel3.setText("Tipo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, -1, -1));

        Pesquise.setText("Pesquise");
        getContentPane().add(Pesquise, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 90, -1));

        jLabel5.setText("Senha");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));
        getContentPane().add(CarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 192, 46));

        jLabel6.setText("Token");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, -1, -1));
        getContentPane().add(CarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 192, 46));
        getContentPane().add(CarNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 192, 46));

        CarToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarTokenActionPerformed(evt);
            }
        });
        getContentPane().add(CarToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 192, 46));

        CarCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarCanalActionPerformed(evt);
            }
        });
        getContentPane().add(CarCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 192, 46));
        getContentPane().add(CarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 192, 46));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 140, 46));

        CarregarCampos.setText("Carregar Campos");
        CarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregarCamposActionPerformed(evt);
            }
        });
        getContentPane().add(CarregarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 140, 50));

        CarID.setEditable(false);
        getContentPane().add(CarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 409, 77, 38));

        btnAlterar.setText("Editar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 140, 46));

        jLabel7.setText("ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaActionPerformed(evt);
            }
        });
        pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisaKeyReleased(evt);
            }
        });
        getContentPane().add(pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 540, 40));

        jLabel8.setText("Usuario");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_padrao.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1010, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
      
        frmAnteLoginGUI objfrmantelogingui = new frmAnteLoginGUI();
        objfrmantelogingui.setVisible(true); //abri a pagina se o login for correto

        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCadastrarCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCanalActionPerformed
        frmAdicionarCanalGUI objadicionarcanalgui = new frmAdicionarCanalGUI();
        objadicionarcanalgui.setVisible(true); //abri a pagina se o login for correto

        dispose();
    }//GEN-LAST:event_btnCadastrarCanalActionPerformed

    private void CarTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarTokenActionPerformed

    private void CarCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarCanalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarCanalActionPerformed

    private void CarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregarCamposActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_CarregarCamposActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
//          System.out.println("Linha selecionada: "+tabelaCanais.getSelectedRow());
      if(tabelaCanais.getSelectedRow() != -1){

      DefaultTableModel model = (DefaultTableModel) tabelaCanais.getModel();
      model.removeRow(tabelaCanais.getSelectedRow());
      
      }else{
           JOptionPane.showMessageDialog(null, "Selecione um Canal para excluir!");
      }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        AlterarCanal();
        ListarValoresCanais();
        LimparCampos();
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaActionPerformed

    private void pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaKeyReleased
        try{
            Vector cabecalho = new Vector();
            cabecalho.add ("id");
            cabecalho.add ("nome");
            cabecalho.add ("canal");
            cabecalho.add ("token");
            cabecalho.add ("tipo");
            cabecalho.add ("usuario");
            if (!pesquisa.getText().equals("")){
                DefaultTableModel nv = new DefaultTableModel(DAO.pesquisar(pesquisa.getText()),cabecalho);
                tabelaCanais.setModel(nv);
            } else {
                DefaultTableModel nv = new DefaultTableModel (new Vector(),cabecalho);
                tabelaCanais.setModel(nv);
            }
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_pesquisaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListaUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListaUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListaUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListaUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListaUserGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CarCanal;
    private javax.swing.JTextField CarID;
    private javax.swing.JTextField CarNome;
    private javax.swing.JPasswordField CarSenha;
    private javax.swing.JTextField CarTipo;
    private javax.swing.JTextField CarToken;
    private javax.swing.JTextField CarUsuario;
    private javax.swing.JButton CarregarCampos;
    private javax.swing.JLabel Pesquise;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrarCanal;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pesquisa;
    private javax.swing.JTable tabelaCanais;
    // End of variables declaration//GEN-END:variables

    private void ListarValoresCanais() {
        try {
            UsuarioDAO objcanaisDAO = new UsuarioDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaCanais.getModel();
            model.setNumRows(0);

            ArrayList<CanaisDTO> lista = objcanaisDAO.listarCanais();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId(),
                    lista.get(num).getNome(),
                    lista.get(num).getCanal(),
                    lista.get(num).getTipo(),
                    lista.get(num).getUsuario(),
                    lista.get(num).getSenha(),
                    lista.get(num).getToken(),});
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ListarValoresView" + erro);

        }

    }
    
    private void CarregarCampos(){
        int setar = tabelaCanais.getSelectedRow();
        CarID.setText(tabelaCanais.getModel().getValueAt(setar, 0).toString());
        CarNome.setText(tabelaCanais.getModel().getValueAt(setar, 1).toString());
        CarCanal.setText(tabelaCanais.getModel().getValueAt(setar, 2).toString());
        CarTipo.setText(tabelaCanais.getModel().getValueAt(setar, 3).toString());
        CarUsuario.setText(tabelaCanais.getModel().getValueAt(setar, 4).toString());
        CarSenha.setText(tabelaCanais.getModel().getValueAt(setar, 5).toString());
        CarToken.setText(tabelaCanais.getModel().getValueAt(setar, 6).toString());
    }
    
 private void ExcluirCadastro(){
     int id_cadastro;
     
     id_cadastro = Integer.parseInt(CarID.getText());
     
     CanaisDTO objcanaisdto = new CanaisDTO();
     objcanaisdto.setId(id_cadastro);
     
     UsuarioDAO objusuariodao = new UsuarioDAO();
     objusuariodao.excluirCadastros(objcanaisdto);

     
    }
    
 private void LimparCampos(){
     CarID.setText("");
     CarNome.setText("");
     CarCanal.setText("");
     CarTipo.setText("");
     CarUsuario.setText("");
     CarSenha.setText("");
     CarToken.setText("");
     CarNome.requestFocus();
 }
 
 private void AlterarCanal(){
     int id_canal;
     String nome_canal, canal_canal, tipo_canal, usuario_canal, senha_canal, token_canal;
     
     id_canal = Integer.parseInt(CarID.getText());
     nome_canal = CarNome.getText();
     canal_canal = CarCanal.getText();
     tipo_canal = CarTipo.getText();
     usuario_canal = CarUsuario.getText();
     senha_canal = CarSenha.getText();
     token_canal = CarToken.getText();
     
     CanaisDTO objcanaisdto = new CanaisDTO();
     objcanaisdto.setId(id_canal);
     objcanaisdto.setNome(nome_canal);
     objcanaisdto.setCanal(canal_canal);
     objcanaisdto.setTipo(tipo_canal);
     objcanaisdto.setUsuario(usuario_canal);
     objcanaisdto.setSenha(senha_canal);
     objcanaisdto.setToken(token_canal);
 
     
     UsuarioDAO objusuariodao = new UsuarioDAO();
     objusuariodao.alterarCadastro(objcanaisdto);
             
 }
 
 
 

}
